//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadxTramite
    {
        public int Id { get; set; }
        public Nullable<int> Id_tramite { get; set; }
        public Nullable<int> Id_Actividad { get; set; }
        public Nullable<int> Posicion { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Tramites Tramites { get; set; }
    }
}
