//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Simultaneo { get; set; }
        public string Actividad_Dependiente { get; set; }
     
    }
}
