//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdo_fox
    {
        public int ID { get; set; }
        public string REFERENCIA1 { get; set; }
        public string INMUEBLE { get; set; }
        public string NEGOCIO { get; set; }
        public string FECHANEGOCIO { get; set; }
        public string CONCEPTO { get; set; }
        public string FECHACUOTA { get; set; }
        public string ANO { get; set; }
        public string MES { get; set; }
        public string DIA { get; set; }
        public Nullable<decimal> VLRCUOTA { get; set; }
        public Nullable<decimal> PAGOCUOTA { get; set; }
        public Nullable<decimal> SALDOXCOBRAR { get; set; }
        public string FECHACARTERA { get; set; }
        public string CODCRM { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> CODIGOTAREA { get; set; }
    }
}
