//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuerdo_pago
    {
        public int ID_AC_PF { get; set; }
        public string NO_ACUERDO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<decimal> VALOR_CUOTA { get; set; }
        public string CUOTA { get; set; }
    }
}
