//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public int Id { get; set; }
        public string Zona { get; set; }
        public Nullable<int> PosicionItem { get; set; }
        public string Item { get; set; }
    }
}
