//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    public partial class bancos
    {
        public bancos()
        {
            this.Tramites = new HashSet<Tramites>();
        }
    
        public int ID_BANCO { get; set; }
        public string NOMBRE_BANCO { get; set; }
    
        [XmlIgnore]  public virtual ICollection<Tramites> Tramites { get; set; }
    }
}
