//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora_tareas
    {
        public int IDBITACORA { get; set; }
        public Nullable<int> TAREA { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> FECHAMOD { get; set; }
    }
}
