//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion_negocio
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Proyecto { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
