//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public empresas()
        {
            this.clientes = new HashSet<clientes>();
            this.clientes1 = new HashSet<clientes>();
        }
    
        public int ID_EMP { get; set; }
        public string NOMBRE_EMP { get; set; }
        public string TEL_EMP { get; set; }
    
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual ICollection<clientes> clientes1 { get; set; }
    }
}
