//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entregas
    {
        public Entregas()
        {
            this.INMUEBLES_ENTREGAS = new HashSet<INMUEBLES_ENTREGAS>();
        }
    
        public int ID_ENTREGAS { get; set; }
        public System.DateTime FECHAREG { get; set; }
        public string ID_PROYECTO { get; set; }
        public string DIROBRA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> ENVIADO { get; set; }
        public string ENVIADOA { get; set; }
        public string ENVIADOPOR { get; set; }
        public int CONSECUTIVO { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual ICollection<INMUEBLES_ENTREGAS> INMUEBLES_ENTREGAS { get; set; }
    }
}
