//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
   using System.Xml.Serialization;        public partial class historial_inmueble
    {
        public int ID_HISTORIAL { get; set; }
        public string CLIENTE { get; set; }
        public string INMUEBLE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION_S { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
