//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_clientes
    {
        public int ID_HISTORIAL { get; set; }
        public string CLIENTEH { get; set; }
        public string TRABAJADOR { get; set; }
        public string DESCRIPCIONH { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual clientes clientes1 { get; set; }
        public virtual trabajadores trabajadores { get; set; }
        public virtual trabajadores trabajadores1 { get; set; }
    }
}
