//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAval
    {
        public int Id { get; set; }
        public Nullable<int> IdAval { get; set; }
        public string Ambiente { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Item { get; set; }
        public Nullable<int> Cumple { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FechaRecibido { get; set; }
        public string UsuarioAprueba { get; set; }
    }
}
