//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
   using System.Xml.Serialization;        public partial class negocio_fox
    {
        public int ID { get; set; }
        public string SUCURSAL { get; set; }
        public string PROYECTO { get; set; }
        public string PPTO { get; set; }
        public string BLOQUE { get; set; }
        public string NOMBREBLOQUE { get; set; }
        public string NEGOCIO { get; set; }
        public string CODICLIENTE { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string FECHANEGOCIO { get; set; }
        public Nullable<decimal> VLRNEGOCIO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> VLRSUBSIDIO { get; set; }
        public string DESISTIDO { get; set; }
        public string FECHADESISTIDO { get; set; }
        public string USUARIO { get; set; }
        public string FECHACREACION { get; set; }
        public string CODIGOVENDEDORA { get; set; }
        public string GASTOSNOTARIALES { get; set; }
        public string ESCRITURADO { get; set; }
        public string SUBROGACION { get; set; }
        public string ORDENPEDIDO { get; set; }
        public Nullable<decimal> VLRINICIALCUOTA { get; set; }
        public Nullable<decimal> VLRCREDITO { get; set; }
        public string CODIGOCRM { get; set; }
        public string OBSERVACIONDESISTIMIENTO { get; set; }
        public string DESCUENTOSFINANCIEROS { get; set; }
        public Nullable<decimal> VLRDIRECTOCREDITO { get; set; }
        public Nullable<decimal> VLRARRAS { get; set; }
        public string TIPOCONTRATO { get; set; }
        public string CAUSADESISTIMIENTO { get; set; }
        public Nullable<decimal> VLRDEVUELTOCLIENTE { get; set; }
        public string NEGOCIOCEDIDO { get; set; }
        public string FECHADECESION { get; set; }
        public string NUEVOPEDIDOCEDIDO { get; set; }
        public string VIENEDESECION { get; set; }
        public string PEDIDODEDONDESECEDIO { get; set; }
        public string AUTORIZADOAESCRITURAR { get; set; }
        public string AUTORIZADOAESCRITURARNOTARIA { get; set; }
        public string SALDOPORPAGARDELACUOTAINICIAL { get; set; }
        public string CODIGOINMUEBLE { get; set; }
    }
}
