//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class negocio
    {
        public string ID_NEGOCIO { get; set; }
        public Nullable<System.DateTime> FECHA_NEGOCIO { get; set; }
        public string PROPIETARIO { get; set; }
        public string CEDULA_P { get; set; }
        public Nullable<System.DateTime> EXPEDICION { get; set; }
        public Nullable<decimal> AREA_PRIVADA { get; set; }
        public Nullable<decimal> AREA_CONSTRUIDA { get; set; }
        public string ESTADO_C { get; set; }
        public Nullable<System.DateTime> FECHA_NACI { get; set; }
        public string LUGAR { get; set; }
        public string PARQUEADERO { get; set; }
        public string AREAS_COMUNES { get; set; }
        public string DIRECCION_R { get; set; }
        public string TELEFONO_P { get; set; }
        public string EMPRESA { get; set; }
        public string TELFONO_EMP { get; set; }
        public string CARGO { get; set; }
        public string PROFESION { get; set; }
        public string DIRECCION_EMPR { get; set; }
        public string ANTIGUEDAD { get; set; }
        public string CORREO { get; set; }
        public string NOMBRE_CONY { get; set; }
        public Nullable<int> TIPO_DOCUMENTO_CONY { get; set; }
        public string LUGAR_EXPEDICION { get; set; }
        public Nullable<System.DateTime> FECHA_EXPEDICION_CUY { get; set; }
        public string CEDULA_CUY { get; set; }
        public string TELE_CONY { get; set; }
        public Nullable<int> N_HIJO { get; set; }
        public string INTERES_COM { get; set; }
        public string PROYECTO_INT { get; set; }
        public string VALOR_CASA { get; set; }
        public string INICIAL { get; set; }
        public Nullable<decimal> ADICIONES_EXCLUSIONES { get; set; }
        public Nullable<decimal> SUBSIDIO { get; set; }
        public Nullable<decimal> GARAJE { get; set; }
        public Nullable<decimal> SALDO_FINANCIAR { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_SERVICIOGAS { get; set; }
        public Nullable<decimal> INTERESES_SUBROGACION { get; set; }
        public string CREDITO { get; set; }
        public Nullable<int> BANCO { get; set; }
        public string NO_CREDITO { get; set; }
        public Nullable<System.DateTime> FECHA_ES { get; set; }
        public Nullable<System.DateTime> FECHA_ENT { get; set; }
        public Nullable<System.DateTime> FECHA_SUBRO { get; set; }
        public string ASESOR_INFO { get; set; }
        public string MEDIO_ENT { get; set; }
        public string ASOCIADO { get; set; }
        public string CLASE_INMU { get; set; }
        public Nullable<int> AUT_MENSAJE { get; set; }
        public Nullable<int> AUT_CORREO { get; set; }
        public int ID_HOJA { get; set; }
        public Nullable<int> SEPARACION { get; set; }
        public string CODIGO_F { get; set; }
        public string USER_CREO { get; set; }
        public string USER_CARTERA { get; set; }
        public Nullable<decimal> INGRESO { get; set; }
        public string DOCUMENTO { get; set; }
    }
}
