//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
   using System.Xml.Serialization;        public partial class NegocioView
    {
        public string ID_NEGOCIO { get; set; }
        public string PROPIETARIO { get; set; }
        public string CEDULA_P { get; set; }
        public string ESTADO_C { get; set; }
        public Nullable<System.DateTime> EXPEDICION { get; set; }
        public Nullable<System.DateTime> FECHA_NACI { get; set; }
        public string LUGAR { get; set; }
        public string DIRECCION_R { get; set; }
        public string TELEFONO_P { get; set; }
        public string EMPRESA { get; set; }
        public string TELFONO_EMP { get; set; }
        public string CARGO { get; set; }
        public string PROFESION { get; set; }
        public string DIRECCION_EMPR { get; set; }
        public string ANTIGUEDAD { get; set; }
        public string CORREO { get; set; }
        public string NOMBRE_CONY { get; set; }
        public string CEDULA_CUY { get; set; }
        public string TELE_CONY { get; set; }
        public Nullable<int> N_HIJO { get; set; }
        public string INTERES_COM { get; set; }
        public string VALOR_CASA { get; set; }
        public string INICIAL { get; set; }
        public string CREDITO { get; set; }
        public string BANCO { get; set; }
        public string NO_CREDITO { get; set; }
        public Nullable<System.DateTime> FECHA_ES { get; set; }
        public Nullable<System.DateTime> FECHA_ENT { get; set; }
        public Nullable<System.DateTime> FECHA_SUBRO { get; set; }
        public string ASESOR_INFO { get; set; }
        public string MEDIO_ENT { get; set; }
        public string ASOCIADO { get; set; }
        public string CLASE_INMU { get; set; }
        public int ID_HOJA { get; set; }
        public Nullable<int> SEPARACION { get; set; }
        public string NOMBRES { get; set; }
        public string NOMBRE_PROYEC { get; set; }
        public Nullable<decimal> INGRESO { get; set; }
    }
}
