//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
   using System.Xml.Serialization;        public partial class pagos_fox
    {
        public int ID { get; set; }
        public string Referencia1 { get; set; }
        public string Obra { get; set; }
        public string Codterc { get; set; }
        public string Nit { get; set; }
        public string Recibo { get; set; }
        public string Nrecibo { get; set; }
        public string Estado { get; set; }
        public string Fecharecibo { get; set; }
        public string Concepto { get; set; }
        public string Vlrrecibo { get; set; }
        public string Nconsignacion { get; set; }
        public string Fechaconsignacion { get; set; }
        public string Vlrcuotaaplicado { get; set; }
        public string Detallecuota { get; set; }
        public string Usuario { get; set; }
        public string Fechaelaboracion { get; set; }
        public string Ncheque { get; set; }
        public string Nota { get; set; }
    }
}
