//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class planos_Proyectos
    {
        public int ID_PLA { get; set; }
        public string PROYECT { get; set; }
        public byte[] IMAGEN { get; set; }
        public string TIPO_IMG { get; set; }
    
        public virtual proyectos proyectos { get; set; }
    }
}
