//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postventa
    {
        public int Id { get; set; }
        public string CedulaP { get; set; }
        public string CodCRM { get; set; }
        public string Proyecto { get; set; }
        public string Mzna { get; set; }
        public string CodInmueble { get; set; }
        public string Propietario { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Descripcion { get; set; }
        public string NombreAdjunto { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
