//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramites_Inmueble
    {
        public int id { get; set; }
        public Nullable<int> id_Tramite { get; set; }
        public string Id_Inmueble { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
    
        public virtual Tramites Tramites { get; set; }
    }
}
