//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAsesoresT
    {
        public Nullable<int> CONTADOR { get; set; }
        public string NOMBRES { get; set; }
        public string T_CEDULA { get; set; }
    }
}
