//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vclientes
    {
        public string CEDULA { get; set; }
        public string NOMBRE_EMP { get; set; }
        public string NOMBRES { get; set; }
        public string P_APELLIDO { get; set; }
        public string S_APELLIDO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string DIRECCION { get; set; }
        public string BARRIO { get; set; }
        public string TELEFONO2 { get; set; }
        public string PROYEC_INTERES { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> EMPRESA { get; set; }
        public string SUELDO { get; set; }
        public string PRESU_COMPRA { get; set; }
        public string INMU_INTERES { get; set; }
        public string INTERES_VI { get; set; }
        public string MOT_COMPRA { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<System.DateTime> FECHAMOD { get; set; }
        public string INFORMACION { get; set; }
        public Nullable<int> ID_EMP { get; set; }
        public string TRABAJADOR { get; set; }
        public string TEL_EMP { get; set; }
        public string NOMBRE_SALA { get; set; }
        public string ASOCIADO { get; set; }
        public string ASESOR { get; set; }
        public Nullable<int> TIPO_PERSONA { get; set; }
        public Nullable<int> TIPO_DOCUMENTO { get; set; }
        public string DIRECCION_CORRESPON { get; set; }
        public string CELULAR { get; set; }
    }
}
