//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCLienteinmueble
    {
        public string NOMBRES { get; set; }
        public string P_APELLIDO { get; set; }
        public string S_APELLIDO { get; set; }
        public string DIRECCION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> DIAS_T { get; set; }
        public Nullable<int> DIAS { get; set; }
        public string PROYEC_INTERES { get; set; }
        public string ASESOR { get; set; }
        public string INMUDECS { get; set; }
        public Nullable<decimal> VAL_INMUEBLE { get; set; }
        public string REFERENCIA { get; set; }
        public string ESTADO { get; set; }
        public string CLIENTE { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRE_PROYEC { get; set; }
        public string TELEFONO2 { get; set; }
        public string BARRIO { get; set; }
        public string INMUEBLE { get; set; }
        public Nullable<System.DateTime> FECHASEPARACION { get; set; }
        public Nullable<System.DateTime> FECHAFINAL { get; set; }
        public string ESTADO_C { get; set; }
    }
}
