//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VInmueblesConTramites
    {
        public Nullable<int> IdTraInmueble { get; set; }
        public string REFERENCIA { get; set; }
        public string INMUOBRA { get; set; }
        public string NOMBRE_BLO { get; set; }
        public string INMUEBLE { get; set; }
        public string PROYECTO_INT { get; set; }
        public string ID_NEGOCIO { get; set; }
        public string PROPIETARIO { get; set; }
        public string CEDULA_P { get; set; }
        public Nullable<int> BANCO { get; set; }
        public string Tramite { get; set; }
        public Nullable<int> IdTramite { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string CODIGO_F { get; set; }
        public string USER_CARTERA { get; set; }
    }
}
