//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
   using System.Xml.Serialization;        public partial class VinteresProyect
    {
        public Nullable<int> CONTADOR { get; set; }
        public string NOMBRE_PROYEC { get; set; }
        public string PROYEC_INTERES { get; set; }
        public string ID_PROYEC { get; set; }
    }
}
