//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaAVal
    {
        public int id { get; set; }
        public Nullable<int> Registro { get; set; }
        public string Propietario { get; set; }
        public string Residente { get; set; }
        public string Inspeccion { get; set; }
        public Nullable<int> Aprueba { get; set; }
        public string UsuarioAprueba { get; set; }
        public Nullable<System.DateTime> FechaFinApro { get; set; }
        public string NOMBRE_PROYEC { get; set; }
        public string NOMBRE_BLO { get; set; }
    }
}
