//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaAvalAntes
    {
        public string NOMBRE_PROYEC { get; set; }
        public string NOMBRE_BLO { get; set; }
        public string INMUOBRA { get; set; }
        public string MZA { get; set; }
        public string INMUEBLE { get; set; }
        public string REFERENCIA { get; set; }
        public string NOMBRECLIENTE { get; set; }

    }
}
