//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VnegocioFox
    {
        public string NOMBREBLOQUE { get; set; }
        public string CEDULA_P { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string CODIGOINMUEBLE { get; set; }
        public string CODIGOCRM { get; set; }
        public string SUCURSAL { get; set; }
        public string NEGOCIO { get; set; }
        public int ID { get; set; }
    }
}
