//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNegocioscompromisos
    {
        public int ID { get; set; }
        public Nullable<decimal> VLRCUOTA { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string CEDULA_P { get; set; }
        public string NOMBREBLOQUE { get; set; }
        public string REFERENCIA1 { get; set; }
        public Nullable<decimal> VLRCREDITO { get; set; }
        public Nullable<decimal> VLRNEGOCIO { get; set; }
        public Nullable<decimal> VLRINICIALCUOTA { get; set; }
        public string CODCRM { get; set; }
        public Nullable<int> CODIGOTAREA { get; set; }
        public Nullable<decimal> SALDOXCOBRAR { get; set; }
        public string FECHACARTERA { get; set; }
        public string TELEFONO_P { get; set; }
        public string TELFONO_EMP { get; set; }
    }
}
