//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VnegocioFox
    {
        public string CodNegocio { get; set; }
        public string NOMBREBLOQUE { get; set; }
        public string CEDULA_P { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string CODIGOINMUEBLE { get; set; }
        public string CODIGOCRM { get; set; }
        public string SUCURSAL { get; set; }
        public string NEGOCIO { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> VLRCREDITO { get; set; }
        public Nullable<decimal> VLRINICIALCUOTA { get; set; }
        public Nullable<decimal> VLRNEGOCIO { get; set; }
        public string FECHANEGOCIO { get; set; }
        public string DOCUMENTO { get; set; }
        public string TELEFONO_P { get; set; }
        public string TELFONO_EMP { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FECHA_ES { get; set; }
        public string USER_CREO { get; set; }
    }
}
