//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPostventa
    {
        public string ID_BLOQUE { get; set; }
        public string CEDULA_P { get; set; }
        public string CODIGO_F { get; set; }
        public string NOMBRE_PROYEC { get; set; }
        public string NOMBRE_BLO { get; set; }
        public string INMUEBLE { get; set; }
        public string PROPIETARIO { get; set; }
        public string TELEFONO_P { get; set; }
        public string CORREO { get; set; }
    }
}
