//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vspt
    {
        public string NOMBRE_PROYEC { get; set; }
        public string T_CEDULA { get; set; }
        public string ID_PROYEC { get; set; }
        public int ID_PY { get; set; }
        public string NOMBRES { get; set; }
        public string TRABAJADOR { get; set; }
        public string ESTADO { get; set; }
        public int CONTADOR { get; set; }
    
    }
}
