//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VtareasNegocio
    {
        public int ID_TAREA { get; set; }
        public string CLIENTE { get; set; }
        public string TRABAJADOR { get; set; }
        public string CONCEPTO { get; set; }
        public string NEGOCIO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public string NOMBRES { get; set; }
    }
}
