//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTramitesBancos
    {
        public Nullable<int> IdBanco { get; set; }
        public string NombreBanco { get; set; }
        public int IdTramite { get; set; }
        public string NombreTramite { get; set; }
        public Nullable<int> IdActividad { get; set; }
        public string NombreActividad { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string NombreDocumento { get; set; }
    }
}
