CREATE TABLE [dbo].[bancos] (
    [ID_BANCO]     INT          IDENTITY (1, 1) NOT NULL,
    [NOMBRE_BANCO] VARCHAR (80) NULL,
    CONSTRAINT [PK__bancos__1579AAABFED8F64B] PRIMARY KEY CLUSTERED ([ID_BANCO] ASC)
);



