CREATE TABLE [dbo].[clientes] (
    [CEDULA]         VARCHAR (13) NOT NULL,
    [NOMBRES]        VARCHAR (50) NULL,
    [P_APELLIDO]     VARCHAR (40) NULL,
    [S_APELLIDO]     VARCHAR (40) NULL,
    [ESTADO_CIVIL]   VARCHAR (30) NULL,
    [DIRECCION]      VARCHAR (60) NOT NULL,
    [BARRIO]         VARCHAR (50) NULL,
    [TELEFONO2]      VARCHAR (13) NULL,
    [PROYEC_INTERES] VARCHAR (10) NULL,
    [EMAIL]          VARCHAR (50) NULL,
    [EMPRESA]        INT          NULL,
    [SUELDO]         VARCHAR (60) NULL,
    [PRESU_COMPRA]   VARCHAR (40) NULL,
    [INMU_INTERES]   VARCHAR (20) NULL,
    [INTERES_VI]     VARCHAR (30) NULL,
    [MOT_COMPRA]     VARCHAR (12) NULL,
    [SALA_VENTA]     INT          NULL,
    [ASESOR]         VARCHAR (30) NULL,
    [FECHACREACION]  DATE         NULL,
    [FECHAMOD]       DATE         NULL,
    [INFORMACION]    VARCHAR (80) NULL,
    [ESTADO]         VARCHAR (1)  NULL,
    [ASOCIADO]       VARCHAR (15) CONSTRAINT [DF__clientes__ASOCIA__53CD4F35] DEFAULT ((0)) NULL,
    CONSTRAINT [PK__clientes__06BB8449A6A3D2A3] PRIMARY KEY CLUSTERED ([CEDULA] ASC),
    FOREIGN KEY ([EMPRESA]) REFERENCES [dbo].[empresas] ([ID_EMP]),
    FOREIGN KEY ([EMPRESA]) REFERENCES [dbo].[empresas] ([ID_EMP]),
    CONSTRAINT [FK__clientes__ASESOR__0697FACD] FOREIGN KEY ([ASESOR]) REFERENCES [dbo].[trabajadores] ([T_CEDULA]),
    CONSTRAINT [FK__clientes__PROYEC__32E0915F] FOREIGN KEY ([PROYEC_INTERES]) REFERENCES [dbo].[proyectos] ([ID_PROYEC])
);



