CREATE TABLE [dbo].[Entregas] (
    [ID_ENTREGAS] INT          IDENTITY (1, 1) NOT NULL,
    [FECHAREG]    DATETIME     NOT NULL,
    [ID_PROYECTO] VARCHAR (10) NULL,
    [DIROBRA]     VARCHAR (50) NULL,
    [USUARIO]     VARCHAR (50) NULL,
    [ENVIADO]     DATETIME     NULL,
    [ENVIADOA]    VARCHAR (50) NULL,
    [ENVIADOPOR]  VARCHAR (50) NULL,
    [CONSECUTIVO] INT          NOT NULL,
    CONSTRAINT [PK_Entregas] PRIMARY KEY CLUSTERED ([ID_ENTREGAS] ASC),
    CONSTRAINT [FK_Entregas_proyectos] FOREIGN KEY ([ID_PROYECTO]) REFERENCES [dbo].[proyectos] ([ID_PROYEC])
);

