CREATE TABLE [dbo].[INMUEBLES_ENTREGAS] (
    [ID_INMUEBLES_ENTREGAS] INT          IDENTITY (1, 1) NOT NULL,
    [ID_ENTREGA]            INT          NULL,
    [REFERENCIA_INMUEBLE]   VARCHAR (16) NULL,
    [FECHAREG]              DATETIME     NULL,
    [CONFIRMAOBRA]          INT          NULL,
    [FECHACONFIRMA]         DATETIME     NULL,
    [INSPECCIONCAL]         VARCHAR (20) NULL,
    [ESTADOAVAL]            INT          NULL,
    [RADICADOVENTA]         DATE         NULL,
    [ENTREGAOBRA]           DATE         NULL,
    [FECHACLIENTE]          DATE         NULL,
    [ESTADOENTREGA]         INT          NULL,
    [FECHAENTREGA]          DATE         NULL,
    CONSTRAINT [PK_INMUEBLES_ENTREGAS] PRIMARY KEY CLUSTERED ([ID_INMUEBLES_ENTREGAS] ASC),
    CONSTRAINT [FK_INMUEBLES_ENTREGAS_Entregas] FOREIGN KEY ([ID_ENTREGA]) REFERENCES [dbo].[Entregas] ([ID_ENTREGAS]),
    CONSTRAINT [FK_INMUEBLES_ENTREGAS_inmuebles] FOREIGN KEY ([REFERENCIA_INMUEBLE]) REFERENCES [dbo].[inmuebles] ([REFERENCIA])
);

