CREATE TABLE [dbo].[negocio] (
    [ID_NEGOCIO]            VARCHAR (50)    NOT NULL,
    [CLASE_INMU]            VARCHAR (45)    NULL,
    [FECHA_NEGOCIO]         DATETIME        NULL,
    [AREA_PRIVADA]          DECIMAL (20, 2) NULL,
    [AREA_CONSTRUIDA]       DECIMAL (20, 2) NULL,
    [PARQUEADERO]           VARCHAR (250)   NULL,
    [AREAS_COMUNES]         VARCHAR (250)   NULL,
    [PROPIETARIO]           VARCHAR (40)    NULL,
    [ESTADO_C]              VARCHAR (30)    NULL,
    [CEDULA_P]              VARCHAR (13)    NULL,
    [LUGAR_EXPE]            NVARCHAR (MAX)  NULL,
    [EXPEDICION]            DATE            NULL,
    [FECHA_NACI]            DATE            NULL,
    [LUGAR]                 VARCHAR (250)   NULL,
    [N_HIJO]                INT             NULL,
    [DOMICILIO]             NVARCHAR (MAX)  NULL,
    [DIRECCION_R]           VARCHAR (250)   NULL,
    [TELEFONO_P]            VARCHAR (13)    NULL,
    [CORREO]                VARCHAR (250)   NULL,
    [EMPRESA]               VARCHAR (100)   NULL,
    [CARGO]                 VARCHAR (100)   NULL,
    [TELFONO_EMP]           VARCHAR (13)    NULL,
    [PROFESION]             VARCHAR (100)   NULL,
    [DIRECCION_EMPR]        VARCHAR (250)   NULL,
    [INGRESO]               DECIMAL (20, 2) NULL,
    [ANTIGUEDAD]            VARCHAR (60)    NULL,
    [NOMBRE_CONY]           VARCHAR (150)   NULL,
    [TIPO_DOCUMENTO_CONY]   VARCHAR (30)    NULL,
    [LUGAR_EXPEDICION]      VARCHAR (250)   NULL,
    [FECHA_EXPEDICION_CUY]  DATETIME        NULL,
    [CEDULA_CUY]            VARCHAR (13)    NULL,
    [TELE_CONY]             VARCHAR (12)    NULL,
    [INTERES_COM]           VARCHAR (100)   NULL,
    [PROYECTO_INT]          VARCHAR (20)    NULL,
    [VALOR_CASA]            VARCHAR (20)    NULL,
    [INICIAL]               VARCHAR (20)    NULL,
    [ADICIONES_EXCLUSIONES] DECIMAL (20, 2) NULL,
    [SUBSIDIO]              DECIMAL (20, 2) NULL,
    [GARAJE]                DECIMAL (20, 2) NULL,
    [DESCUENTO]             DECIMAL (20, 2) NULL,
    [VALOR_SERVICIOGAS]     DECIMAL (20, 2) NULL,
    [INTERESES_SUBROGACION] DECIMAL (20, 2) NULL,
    [CREDITO]               VARCHAR (20)    NULL,
    [BANCO]                 INT             NULL,
    [NO_CREDITO]            VARCHAR (30)    NULL,
    [FECHA_ES]              DATE            NULL,
    [FECHA_ENT]             DATE            NULL,
    [FECHA_SUBRO]           DATE            NULL,
    [ASESOR_INFO]           VARCHAR (60)    NULL,
    [MEDIO_ENT]             VARCHAR (250)   NULL,
    [ASOCIADO]              VARCHAR (13)    NULL,
    [AUT_MENSAJE]           INT             NULL,
    [AUT_CORREO]            INT             NULL,
    [OBSERVACIONES]         NVARCHAR (MAX)  NULL,
    [ID_HOJA]               INT             IDENTITY (1, 1) NOT NULL,
    [SEPARACION]            INT             NULL,
    [CODIGO_F]              VARCHAR (50)    NULL,
    [USER_CREO]             VARCHAR (60)    NULL,
    [USER_CARTERA]          VARCHAR (60)    NULL,
    [DOCUMENTO]             VARCHAR (400)   NULL,
    CONSTRAINT [PK_negocio] PRIMARY KEY CLUSTERED ([ID_NEGOCIO] ASC, [ID_HOJA] ASC)
);





