CREATE TABLE [dbo].[negocio] (
    [ID_NEGOCIO]     VARCHAR (50)    NOT NULL,
    [PROPIETARIO]    VARCHAR (40)    NULL,
    [CEDULA_P]       VARCHAR (13)    NULL,
    [EXPEDICION]     DATE            NULL,
    [ESTADO_C]       VARCHAR (30)    NULL,
    [FECHA_NACI]     DATE            NULL,
    [LUGAR]          VARCHAR (45)    NULL,
    [DIRECCION_R]    VARCHAR (80)    NULL,
    [TELEFONO_P]     VARCHAR (13)    NULL,
    [EMPRESA]        VARCHAR (40)    NULL,
    [TELFONO_EMP]    VARCHAR (11)    NULL,
    [CARGO]          VARCHAR (45)    NULL,
    [PROFESION]      VARCHAR (60)    NULL,
    [DIRECCION_EMPR] VARCHAR (60)    NULL,
    [ANTIGUEDAD]     VARCHAR (15)    NULL,
    [CORREO]         VARCHAR (40)    NULL,
    [NOMBRE_CONY]    VARCHAR (80)    NULL,
    [CEDULA_CUY]     VARCHAR (13)    NULL,
    [TELE_CONY]      VARCHAR (12)    NULL,
    [N_HIJO]         INT             NULL,
    [INTERES_COM]    VARCHAR (60)    NULL,
    [PROYECTO_INT]   VARCHAR (10)    NULL,
    [VALOR_CASA]     VARCHAR (20)    NULL,
    [INICIAL]        VARCHAR (20)    NULL,
    [CREDITO]        VARCHAR (20)    NULL,
    [BANCO]          VARCHAR (45)    NULL,
    [NO_CREDITO]     VARCHAR (10)    NULL,
    [FECHA_ES]       DATE            NULL,
    [FECHA_ENT]      DATE            NULL,
    [FECHA_SUBRO]    DATE            NULL,
    [ASESOR_INFO]    VARCHAR (60)    NULL,
    [MEDIO_ENT]      VARCHAR (20)    NULL,
    [ASOCIADO]       VARCHAR (13)    NULL,
    [CLASE_INMU]     VARCHAR (45)    NULL,
    [ID_HOJA]        INT             IDENTITY (1, 1) NOT NULL,
    [SEPARACION]     INT             NULL,
    [CODIGO_F]       VARCHAR (50)    NULL,
    [USER_CREO]      VARCHAR (60)    NULL,
    [USER_CARTERA]   VARCHAR (60)    NULL,
    [INGRESO]        DECIMAL (20, 2) NULL,
    [DOCUMENTO]      VARCHAR (400)   NULL,
    CONSTRAINT [PK_negocio] PRIMARY KEY CLUSTERED ([ID_NEGOCIO] ASC, [ID_HOJA] ASC)
);

