CREATE TABLE [dbo].[sala_ventas] (
    [ID_SALA]     INT          IDENTITY (1, 1) NOT NULL,
    [NOMBRE_SALA] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_SALA] ASC, [NOMBRE_SALA] ASC),
    UNIQUE NONCLUSTERED ([NOMBRE_SALA] ASC)
);

