CREATE TABLE [dbo].[trabajadores] (
    [T_CEDULA] VARCHAR (30) NOT NULL,
    [NOMBRES]  VARCHAR (25) NULL,
    [EMAIL]    VARCHAR (50) NULL,
    [TIPO]     VARCHAR (50) NULL,
    CONSTRAINT [PK__trabajad__A4FE005A659BBA27] PRIMARY KEY CLUSTERED ([T_CEDULA] ASC)
);

